# SwiftLint Configuration
disabled_rules:
  - trailing_whitespace
  - todo

opt_in_rules:
  - empty_count
  - closure_spacing
  - explicit_init
  - first_where
  - sorted_imports

excluded:
  - Pods
  - .build
  - .swiftpm
  - DerivedData

line_length:
  warning: 120
  error: 150

file_length:
  warning: 500
  error: 800

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 100

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - url
    - URL
    - jwt

reporter: "xcode"
